### ISSUE TITLE
Addon not working for filtered decks

### ISSUE THREAD

**Issue by Ankilli** [iamjustkoi/LeechToolkit#14]
Hey there,

I am sorry I write another post again, don't stress with it 😅
I noticed that cards in a filtered deck are not bothered by my settings in the addon's menu.
Do I have to turn it on or check something for it to do so? :)

Kind regards and happy holidays 😄

**Comment by iamjustkoi** [comment]
Hey!
Yeah, currently I don't have it set up to work with filtered decks right now, actually. 

Since they're custom I didn't want to mess with the main deck from there too much, to be honest, but I can defs consider adding something in the future, if the interest's three. It might take a few more additions and tweaks to put in, but will see!

> Kind regards and happy holidays 😄

Thanks and happy holidays! Wish you the best! ⛄
