### ISSUE TITLE
How to do this..

### ISSUE THREAD

**Issue by Ankilli** [iamjustkoi/LeechToolkit#9]
Hey, I'm struggeling with the right settings, maybe you can help me out :)

When a card is hitting it's leech mark I want four things to happen:
1) Reset the history so the next time I fail the card it's not leeched faster than on the first cycle, just like the first time.
2) Add to New cards so the card goes into learning mode again
3) Have no tagging on the card at all (so no "leech" or anything added.
4) Move the card to a certain deck just for difficult cards where more learning steps are set.

So far this are my settings, but when a card is leeched it does change to a new card again but when I answer it, it just comes around again (I can answer the card unlimited times it just repeats itself on and on even if there are other cards to review as well in that deck)

<img width="584" alt="grafik" src="https://user-images.githubusercontent.com/89978096/206579507-20f76451-6f25-4c8f-b3d4-36fe62e6fd3e.png">

<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/89978096/206579565-34bb380a-789f-4832-a4a5-cd4d09b82728.png">

<img width="576" alt="grafik" src="https://user-images.githubusercontent.com/89978096/206579634-f777d4ac-dbda-4947-9d07-4d7b752ac2ac.png">

<img width="576" alt="grafik" src="https://user-images.githubusercontent.com/89978096/206579683-bc0d609c-44aa-4e8f-91c8-b2cffd427fd9.png">

<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/89978096/206579707-3ba43a35-0c6f-4060-be54-c2396fd1e672.png">

<img width="577" alt="grafik" src="https://user-images.githubusercontent.com/89978096/206579732-f2f06ffb-45d9-4750-b27a-6984d70c1a44.png">

Version: 1.1.1-a5

Cheers :)

Btw.: I can redo UnLeeched cards now, Leech/Un-Leech in the browser without any 'conf' msg.
Thank you A LOT! :)))

**Comment by iamjustkoi** [comment]
Hey!

So, going down the list:

>     1. Reset the history so the next time I fail the card it's not leeched faster than on the first cycle, just like the first time.

For this, under Leech Actions, what you'll want to do is forget the card with lapses set to forget (like what you've got already).

>     2. Add to New cards so the card goes into learning mode again

Here you can actually uncheck forget now, funny enough, and instead just check "Add to new" in Leech Actions! 
Then you can set the insert positions to any range you want and it'll choose a random position between them (e.g. in a queue with 100 new cards, Top +10 ~ Bottom -10 would go from 10 to 90).
The Add to New action also has a couple other options related to matching the cards with other close ones in the new queue (memory recall if ya want).

>     3. Have no tagging on the card at all (so no "leech" or anything added.

Heading back to Leech Actions, you can remove the "leech" tag Anki sets here and you should be good to go! You'll probs also want to disable the sync tag, or maybe change it to something else, in the Advanced tab (looks like you're good to go on that front, too!).

>     4. Move the card to a certain deck just for difficult cards where more learning steps are set.

I think you have this all set up correctly, too. Just set the deck in the Move to Deck option and the card'll move away! 

Looks like I figured out what might've been causing some errors since you asked about this though, lol. Forgot this was set up so, if the deck you wanted to move to didn't already exist, it won't automatically create it for you (which means the deck doesn't really exit, or that there's "None" I guess).

So, for the time being, you might just have to make the deck beforehand, too, actually. It might have some issues with complex names, too, but not sure about that since that part's not my code, pretty much, just wanted to give the warning, just in case!

Hope that helps!

> Btw.: I can redo UnLeeched cards now, Leech/Un-Leech in the browser without any 'conf' msg.
> Thank you A LOT! :)))

You bet! Really happy it's working out for you!
Cheers! 😄

**Comment by Ankilli** [comment]
Thank you for your quick reply at such an hour!🚀👍

**Comment by iamjustkoi** [comment]
No prob, happy I could help!
